version: 2
jobs:
  build:
    working_directory: ~/rapme
    docker:
      - image: circleci/node:8.1.2-browsers
    steps:
      - checkout
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: build
          command: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
  test:
    working_directory: ~/rapme
    docker:
      - image: circleci/node:8.1.2-browsers
    steps:
      - checkout
      - shell:
          name: Install Dependencies
          command: |
            sudo apt-get install default-jdk
      - run:
          name: Install node modules
          command: yarn install
      - run:
          name: test
          command: yarn test
      # - run:
      #     name: code-coverage
      #     command: './node_modules/.bin/nyc report --reporter=text-lcov'
      # - store_artifacts:
      #     path: test-results.xml
      #     prefix: tests
      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
  deploy:
    working_directory: ~/rapme
    docker:
      - image: circleci/node:8.1.2-browsers
    steps:
      - checkout
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: build
          command: yarn build
      - shell:
          name: Install Dependencies
          command: |
            sudo apt-get -y install python-pip python-dev \
            pip install awscli --upgrade \
            export PATH=~/.local/bin:$PATH
      - shell:
          name: Sync with S3 bucket
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync dist/ s3://rapme
            else
              echo "Not master branch so not deploying"
            fi

# https://circleci.com/docs/2.0/worklows/
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build

      - test:
          requires:
            - build
          filters:
            branches:
              only: master

      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
