version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
  test:
    docker:
      - image: selenium/standalone-chrome:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
