version: 2
jobs:
  build:
    working_directory: ~/rapme
    docker:
      - image: circleci/node:8.1.2-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: build
          command: yarn build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
  test:
    working_directory: ~/rapme
    docker:
      - image: circleci/node:8.1.2-browsers
    steps:
      - checkout
      - shell:
          name: Install Dependencies
          command: |
            sudo apt-get install default-jdk
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: test
          command: yarn test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
